// ============================================================
// ثابت‌های Meta سرور — دقیقاً هم‌راستا با src/lib/mock-data.ts فرانت‌اند
// تا وقتی فرانت به این سرور واقعی وصل شود، هیچ ناهماهنگی در
// مقادیر پیش‌فرض/پروفایل‌های ریسک/گروه نماد دیده نشود.
// ============================================================
import type { BotConfig, RiskPreset } from "../types.js";

export const DEFAULT_CONFIG: BotConfig = {
  MT5_LOGIN: 5003330711,
  MT5_PASSWORD: "********",
  MT5_SERVER: "MetaQuotes-Demo",
  MT5_PATH: null,

  SYMBOLS: ["EURUSD", "GBPUSD", "XAUUSD"],
  TIMEFRAME: 15,
  STRATEGY_MODE: "خودکار (تشخیص رژیم بازار)",

  REGIME_ADX_MAX: 35,
  REGIME_BB_SLOPE_LOOKBACK: 6,
  REGIME_BB_SLOPE_MAX_PERCENT: 0.18,
  REGIME_EFFICIENCY_LOOKBACK: 24,
  REGIME_EFFICIENCY_MAX: 0.45,
  REGIME_ATR_LOOKBACK: 96,
  REGIME_ATR_MIN_PERCENTILE: 25,
  REGIME_ATR_MAX_PERCENTILE: 92,

  SCALP_BB_PERIOD: 20,
  SCALP_BB_STD: 2.1,
  SCALP_RSI_PERIOD: 7,
  SCALP_RSI_OVERSOLD: 28,
  SCALP_RSI_OVERBOUGHT: 72,
  SCALP_REQUIRE_REJECTION: true,
  SCALP_REJECTION_WICK_RATIO: 0.55,

  SCALP_STRUCTURE_LOOKBACK: 14,
  SCALP_STRUCTURE_BUFFER_ATR: 0.22,
  SCALP_ATR_SL_MULTIPLIER: 1.15,
  SCALP_TP_MODE: "atr",
  SCALP_TP_ATR_FALLBACK: 1.4,
  SCALP_MIN_RR: 1.4,
  SCALP_MAX_SPREAD_POINTS: 28,
  SCALP_SESSION_FILTER_ENABLED: true,
  SCALP_SESSION_START_HOUR_UTC: 6,
  SCALP_SESSION_END_HOUR_UTC: 21,

  RISK_PERCENT_PER_TRADE: 1.0,
  SL_PERCENT: 0.5,
  TP_PERCENT: 1.0,
  ENABLE_LEVERAGE_AWARE_PERCENT_STOPS: true,
  ENABLE_SR_STOPS: true,
  SR_LOOKBACK_BARS: 30,
  SR_BUFFER_ATR_MULTIPLIER: 0.15,
  ENABLE_DONCHIAN_SL: true,
  DONCHIAN_PERIOD: 20,
  DONCHIAN_ATR_MULTIPLIER: 1.0,
  RISK_TOLERANCE_PROFILE: "متعادل",

  ADX_TREND_THRESHOLD: 25,
  COOLDOWN_BARS: 4,
  MAX_CONCURRENT_TRADES: 3,
  MAX_TOTAL_RISK_PERCENT: 6.0,
  ENABLE_DAILY_LOSS_LIMIT: true,
  DAILY_LOSS_LIMIT_PERCENT: 5.0,
  ENABLE_HTF_CONFIRMATION: true,
  HTF_TIMEFRAME: 60,

  ENABLE_TRAILING_STOP: true,
  TRAILING_ACTIVATION_ATR_MULTIPLIER: 0.8,
  TRAILING_DISTANCE_ATR_MULTIPLIER: 0.6,
  ENABLE_MAX_TRADE_DURATION: true,
  MAX_TRADE_DURATION_HOURS: 12,
  ENABLE_WEEKEND_CLOSE: true,
  WEEKEND_CLOSE_HOUR_UTC: 21,

  REQUIRE_DEMO_ACCOUNT: true,
  PROFILE_NAME: "Default",
  MAGIC_NUMBER: 20240817,
  INITIAL_BALANCE: 10000,
};

export const RISK_PROFILES: Record<string, RiskPreset> = {
  "محافظه‌کار": {
    RISK_PERCENT_PER_TRADE: 0.5, DONCHIAN_PERIOD: 25, DONCHIAN_ATR_MULTIPLIER: 1.2,
    ADX_TREND_THRESHOLD: 28, COOLDOWN_BARS: 6, MAX_CONCURRENT_TRADES: 2, MAX_TOTAL_RISK_PERCENT: 3.0,
    ENABLE_TRAILING_STOP: true, TRAILING_ACTIVATION_ATR_MULTIPLIER: 1.0, TRAILING_DISTANCE_ATR_MULTIPLIER: 0.8,
  },
  "متعادل": {
    RISK_PERCENT_PER_TRADE: 1.0, DONCHIAN_PERIOD: 20, DONCHIAN_ATR_MULTIPLIER: 1.0,
    ADX_TREND_THRESHOLD: 25, COOLDOWN_BARS: 4, MAX_CONCURRENT_TRADES: 3, MAX_TOTAL_RISK_PERCENT: 6.0,
    ENABLE_TRAILING_STOP: true, TRAILING_ACTIVATION_ATR_MULTIPLIER: 0.8, TRAILING_DISTANCE_ATR_MULTIPLIER: 0.6,
  },
  "تهاجمی": {
    RISK_PERCENT_PER_TRADE: 2.0, DONCHIAN_PERIOD: 14, DONCHIAN_ATR_MULTIPLIER: 0.85,
    ADX_TREND_THRESHOLD: 22, COOLDOWN_BARS: 2, MAX_CONCURRENT_TRADES: 5, MAX_TOTAL_RISK_PERCENT: 12.0,
    ENABLE_TRAILING_STOP: true, TRAILING_ACTIVATION_ATR_MULTIPLIER: 0.6, TRAILING_DISTANCE_ATR_MULTIPLIER: 0.45,
  },
};

export const DEFAULT_SYMBOL_GROUPS: Record<string, string[]> = {
  "جفت ارزهای اصلی": ["EURUSD", "GBPUSD", "USDJPY", "USDCHF"],
  "جفت ارزهای فرعی": ["AUDUSD", "NZDUSD", "USDCAD", "AUDJPY"],
  "فلزات": ["XAUUSD", "XAGUSD"],
  "ارزهای دیجیتال": ["BTCUSD", "ETHUSD"],
};

export const TIMEFRAMES: number[] = [1, 5, 15, 30, 60, 240, 1440];
export const BACKTEST_PERIODS: string[] = ["۱ ماه اخیر", "۳ ماه اخیر", "۶ ماه اخیر", "۱ سال اخیر"];
export const STRATEGY_MODES: string[] = [
  "روند (Trend Following)",
  "اسکلپ (Scalping)",
  "خودکار (تشخیص رژیم بازار)",
];
